// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bikeStore.Data;

namespace BikeStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20191201091315_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BikeStore.Data.Entities.BikeJunction", b =>
                {
                    b.Property<long>("BJId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BId");

                    b.Property<int>("BJColor");

                    b.Property<int>("BJSize");

                    b.HasKey("BJId");

                    b.HasIndex("BId");

                    b.ToTable("BikeJunction");

                    b.HasData(
                        new
                        {
                            BJId = 1L,
                            BId = 1L,
                            BJColor = 1,
                            BJSize = 2
                        },
                        new
                        {
                            BJId = 2L,
                            BId = 2L,
                            BJColor = 2,
                            BJSize = 2
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Bike", b =>
                {
                    b.Property<long>("BId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BBrand");

                    b.Property<long>("BCategoryId");

                    b.Property<long?>("BImagesSIId");

                    b.Property<long>("BImgId");

                    b.Property<string>("BModel");

                    b.Property<decimal?>("BPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("BThumbImgContent");

                    b.Property<bool>("IsInStock");

                    b.HasKey("BId");

                    b.HasIndex("BCategoryId");

                    b.HasIndex("BImagesSIId");

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            BId = 1L,
                            BBrand = "Specialized",
                            BCategoryId = 5L,
                            BImgId = 0L,
                            BModel = "S-Works Epic AXS",
                            BPrice = 1299.6m,
                            IsInStock = true
                        },
                        new
                        {
                            BId = 2L,
                            BBrand = "Specialized",
                            BCategoryId = 5L,
                            BImgId = 0L,
                            BModel = "Epic Pro",
                            BPrice = 899.5m,
                            IsInStock = true
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.BikeSpecJunction", b =>
                {
                    b.Property<long>("BSJId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BSJBikeId");

                    b.Property<long>("BSJSpecId");

                    b.Property<long?>("BSJSpecificationSpecId");

                    b.HasKey("BSJId");

                    b.HasIndex("BSJBikeId");

                    b.HasIndex("BSJSpecificationSpecId");

                    b.ToTable("BikeSpecJunction");

                    b.HasData(
                        new
                        {
                            BSJId = 1L,
                            BSJBikeId = 1L,
                            BSJSpecId = 1L
                        },
                        new
                        {
                            BSJId = 2L,
                            BSJBikeId = 1L,
                            BSJSpecId = 2L
                        },
                        new
                        {
                            BSJId = 3L,
                            BSJBikeId = 1L,
                            BSJSpecId = 3L
                        },
                        new
                        {
                            BSJId = 4L,
                            BSJBikeId = 1L,
                            BSJSpecId = 4L
                        },
                        new
                        {
                            BSJId = 5L,
                            BSJBikeId = 1L,
                            BSJSpecId = 5L
                        },
                        new
                        {
                            BSJId = 6L,
                            BSJBikeId = 1L,
                            BSJSpecId = 6L
                        },
                        new
                        {
                            BSJId = 7L,
                            BSJBikeId = 1L,
                            BSJSpecId = 7L
                        },
                        new
                        {
                            BSJId = 8L,
                            BSJBikeId = 1L,
                            BSJSpecId = 8L
                        },
                        new
                        {
                            BSJId = 9L,
                            BSJBikeId = 1L,
                            BSJSpecId = 9L
                        },
                        new
                        {
                            BSJId = 10L,
                            BSJBikeId = 1L,
                            BSJSpecId = 10L
                        },
                        new
                        {
                            BSJId = 11L,
                            BSJBikeId = 1L,
                            BSJSpecId = 11L
                        },
                        new
                        {
                            BSJId = 12L,
                            BSJBikeId = 1L,
                            BSJSpecId = 12L
                        },
                        new
                        {
                            BSJId = 13L,
                            BSJBikeId = 1L,
                            BSJSpecId = 13L
                        },
                        new
                        {
                            BSJId = 14L,
                            BSJBikeId = 1L,
                            BSJSpecId = 14L
                        },
                        new
                        {
                            BSJId = 15L,
                            BSJBikeId = 1L,
                            BSJSpecId = 15L
                        },
                        new
                        {
                            BSJId = 16L,
                            BSJBikeId = 1L,
                            BSJSpecId = 16L
                        },
                        new
                        {
                            BSJId = 17L,
                            BSJBikeId = 1L,
                            BSJSpecId = 17L
                        },
                        new
                        {
                            BSJId = 18L,
                            BSJBikeId = 1L,
                            BSJSpecId = 18L
                        },
                        new
                        {
                            BSJId = 19L,
                            BSJBikeId = 1L,
                            BSJSpecId = 19L
                        },
                        new
                        {
                            BSJId = 20L,
                            BSJBikeId = 1L,
                            BSJSpecId = 20L
                        },
                        new
                        {
                            BSJId = 21L,
                            BSJBikeId = 1L,
                            BSJSpecId = 21L
                        },
                        new
                        {
                            BSJId = 22L,
                            BSJBikeId = 1L,
                            BSJSpecId = 22L
                        },
                        new
                        {
                            BSJId = 23L,
                            BSJBikeId = 1L,
                            BSJSpecId = 23L
                        },
                        new
                        {
                            BSJId = 24L,
                            BSJBikeId = 1L,
                            BSJSpecId = 24L
                        },
                        new
                        {
                            BSJId = 25L,
                            BSJBikeId = 1L,
                            BSJSpecId = 25L
                        },
                        new
                        {
                            BSJId = 26L,
                            BSJBikeId = 2L,
                            BSJSpecId = 26L
                        },
                        new
                        {
                            BSJId = 27L,
                            BSJBikeId = 2L,
                            BSJSpecId = 2L
                        },
                        new
                        {
                            BSJId = 28L,
                            BSJBikeId = 2L,
                            BSJSpecId = 3L
                        },
                        new
                        {
                            BSJId = 29L,
                            BSJBikeId = 2L,
                            BSJSpecId = 27L
                        },
                        new
                        {
                            BSJId = 30L,
                            BSJBikeId = 2L,
                            BSJSpecId = 28L
                        },
                        new
                        {
                            BSJId = 31L,
                            BSJBikeId = 2L,
                            BSJSpecId = 6L
                        },
                        new
                        {
                            BSJId = 32L,
                            BSJBikeId = 2L,
                            BSJSpecId = 7L
                        },
                        new
                        {
                            BSJId = 33L,
                            BSJBikeId = 2L,
                            BSJSpecId = 29L
                        },
                        new
                        {
                            BSJId = 34L,
                            BSJBikeId = 2L,
                            BSJSpecId = 9L
                        },
                        new
                        {
                            BSJId = 35L,
                            BSJBikeId = 2L,
                            BSJSpecId = 30L
                        },
                        new
                        {
                            BSJId = 36L,
                            BSJBikeId = 2L,
                            BSJSpecId = 31L
                        },
                        new
                        {
                            BSJId = 37L,
                            BSJBikeId = 2L,
                            BSJSpecId = 32L
                        },
                        new
                        {
                            BSJId = 38L,
                            BSJBikeId = 2L,
                            BSJSpecId = 33L
                        },
                        new
                        {
                            BSJId = 39L,
                            BSJBikeId = 2L,
                            BSJSpecId = 14L
                        },
                        new
                        {
                            BSJId = 40L,
                            BSJBikeId = 2L,
                            BSJSpecId = 15L
                        },
                        new
                        {
                            BSJId = 41L,
                            BSJBikeId = 2L,
                            BSJSpecId = 16L
                        },
                        new
                        {
                            BSJId = 42L,
                            BSJBikeId = 2L,
                            BSJSpecId = 34L
                        },
                        new
                        {
                            BSJId = 43L,
                            BSJBikeId = 2L,
                            BSJSpecId = 35L
                        },
                        new
                        {
                            BSJId = 44L,
                            BSJBikeId = 2L,
                            BSJSpecId = 36L
                        },
                        new
                        {
                            BSJId = 45L,
                            BSJBikeId = 2L,
                            BSJSpecId = 20L
                        },
                        new
                        {
                            BSJId = 46L,
                            BSJBikeId = 2L,
                            BSJSpecId = 21L
                        },
                        new
                        {
                            BSJId = 47L,
                            BSJBikeId = 2L,
                            BSJSpecId = 37L
                        },
                        new
                        {
                            BSJId = 48L,
                            BSJBikeId = 2L,
                            BSJSpecId = 23L
                        },
                        new
                        {
                            BSJId = 49L,
                            BSJBikeId = 2L,
                            BSJSpecId = 24L
                        },
                        new
                        {
                            BSJId = 50L,
                            BSJBikeId = 2L,
                            BSJSpecId = 38L
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Category", b =>
                {
                    b.Property<long>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatDescr");

                    b.Property<string>("CatName");

                    b.Property<bool>("IsCategoryActive");

                    b.Property<long?>("MainCatId");

                    b.HasKey("CatId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CatId = 1L,
                            CatName = "Mountain",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 2L,
                            CatName = "Road",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 3L,
                            CatName = "Active",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 4L,
                            CatName = "Electric",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 5L,
                            CatName = "Cross Country",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 6L,
                            CatName = "Trail",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 7L,
                            CatName = "Downhill",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 8L,
                            CatName = "Dirt Jump",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 9L,
                            CatName = "Performance",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 10L,
                            CatName = "Adventure & Gravel",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 11L,
                            CatName = "Cyclocross",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 12L,
                            CatName = "Triathlon",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 13L,
                            CatName = "Fitness",
                            IsCategoryActive = true,
                            MainCatId = 3L
                        },
                        new
                        {
                            CatId = 14L,
                            CatName = "Transport",
                            IsCategoryActive = true,
                            MainCatId = 3L
                        },
                        new
                        {
                            CatId = 15L,
                            CatName = "Comfort",
                            IsCategoryActive = true,
                            MainCatId = 3L
                        },
                        new
                        {
                            CatId = 16L,
                            CatName = "Road",
                            IsCategoryActive = true,
                            MainCatId = 4L
                        },
                        new
                        {
                            CatId = 17L,
                            CatName = "Mountain",
                            IsCategoryActive = true,
                            MainCatId = 4L
                        },
                        new
                        {
                            CatId = 18L,
                            CatName = "Active",
                            IsCategoryActive = true,
                            MainCatId = 4L
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.ImgContent", b =>
                {
                    b.Property<long>("ICId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ICContent");

                    b.Property<string>("ICMimeType");

                    b.Property<string>("ICName");

                    b.Property<long?>("StoreImagesSIId");

                    b.HasKey("ICId");

                    b.HasIndex("StoreImagesSIId");

                    b.ToTable("ImgContent");
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Specification", b =>
                {
                    b.Property<long>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SpecBrand");

                    b.Property<long>("SpecCatId");

                    b.Property<string>("SpecDescr");

                    b.Property<string>("SpecModel");

                    b.Property<string>("SpecType");

                    b.HasKey("SpecId");

                    b.HasIndex("SpecCatId");

                    b.ToTable("Specification");

                    b.HasData(
                        new
                        {
                            SpecId = 1L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "(Rainbow)",
                            SpecModel = "XX1",
                            SpecType = "CHAIN"
                        },
                        new
                        {
                            SpecId = 2L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "threaded BB",
                            SpecModel = "DUB",
                            SpecType = "BOTTOM BRACKET"
                        },
                        new
                        {
                            SpecId = 3L,
                            SpecBrand = "QUARQ",
                            SpecCatId = 1L,
                            SpecDescr = "Boost™ 148, DUB, 170/175mm",
                            SpecModel = "XX1 Eagle Power Meter",
                            SpecType = "CRANKSET"
                        },
                        new
                        {
                            SpecId = 4L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "trigger, 12-speed",
                            SpecModel = "XX1 Eagle AXS",
                            SpecType = "SHIFT LEVERS"
                        },
                        new
                        {
                            SpecId = 5L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "10-50t",
                            SpecModel = "XG-1299 Eagle",
                            SpecType = "CASSETTE"
                        },
                        new
                        {
                            SpecId = 6L,
                            SpecBrand = "Alloy",
                            SpecCatId = 1L,
                            SpecDescr = "32T",
                            SpecModel = "",
                            SpecType = "CHAINRINGS"
                        },
                        new
                        {
                            SpecId = 7L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "",
                            SpecModel = "XX1 Eagle AXS",
                            SpecType = "REAR DERAILLEUR"
                        },
                        new
                        {
                            SpecId = 8L,
                            SpecBrand = "RockShox",
                            SpecCatId = 2L,
                            SpecDescr = "top-adjust Brain Fade, tapered carbon crown and steerer, 15x110mm Maxle® Stealth thru-axle, 42mm offset, 100mm of travel",
                            SpecModel = "SID Brain Ultimate",
                            SpecType = "FORK"
                        },
                        new
                        {
                            SpecId = 9L,
                            SpecBrand = "RockShox",
                            SpecCatId = 2L,
                            SpecDescr = "AUTOSAG, 51x257mm",
                            SpecModel = "Custom Micro Brain shock w/ Spike Valve",
                            SpecType = "REAR SHOCK"
                        },
                        new
                        {
                            SpecId = 10L,
                            SpecBrand = "Roval",
                            SpecCatId = 3L,
                            SpecDescr = "sealed cartridge bearings, 15mm thru-axle, 110mm spacing, 24h",
                            SpecModel = "Control SL",
                            SpecType = "FRONT HUB"
                        },
                        new
                        {
                            SpecId = 11L,
                            SpecBrand = "Roval",
                            SpecCatId = 3L,
                            SpecDescr = "DT Swiss Star Ratchet, 54t engagement, SRAM XD driver body, 12mm thru-axle, 148mm spacing, 28h",
                            SpecModel = "Control SL",
                            SpecType = "REAR HUB"
                        },
                        new
                        {
                            SpecId = 12L,
                            SpecBrand = "Presta",
                            SpecCatId = 3L,
                            SpecDescr = "60mm valve",
                            SpecModel = "",
                            SpecType = "INNER TUBES"
                        },
                        new
                        {
                            SpecId = 13L,
                            SpecBrand = "DT Swiss",
                            SpecCatId = 3L,
                            SpecDescr = "Competition Race",
                            SpecModel = "",
                            SpecType = "SPOKES"
                        },
                        new
                        {
                            SpecId = 14L,
                            SpecBrand = "Roval",
                            SpecCatId = 3L,
                            SpecDescr = "hookless carbon, 25mm internal width, tubeless-ready, hand-built",
                            SpecModel = "Control SL",
                            SpecType = "RIMS"
                        },
                        new
                        {
                            SpecId = 15L,
                            SpecBrand = "Specialized",
                            SpecCatId = 3L,
                            SpecDescr = "Control casing, GRIPTON® compound, 60 TPI, 2Bliss Ready, 29x2.3",
                            SpecModel = "Fast Trak",
                            SpecType = "FRONT TIRE"
                        },
                        new
                        {
                            SpecId = 16L,
                            SpecBrand = "Specialized",
                            SpecCatId = 3L,
                            SpecDescr = "Control casing, GRIPTON® compound, 60 TPI, 2Bliss Ready, 29x2.3",
                            SpecModel = "Fast Trak",
                            SpecType = "REAR TIRE"
                        },
                        new
                        {
                            SpecId = 17L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = "carbon fiber rails, carbon fiber base, 143mm",
                            SpecModel = "Body Geometry S-Works Power",
                            SpecType = "SADDLE"
                        },
                        new
                        {
                            SpecId = 18L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = "10mm setback, 30.9mm",
                            SpecModel = "S-Works FACT carbon",
                            SpecType = "SEATPOST"
                        },
                        new
                        {
                            SpecId = 19L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = "alloy, titanium bolts, 6-degree rise",
                            SpecModel = "S-Works SL",
                            SpecType = "STEM"
                        },
                        new
                        {
                            SpecId = 20L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = "6-degree upsweep, 8-degree backsweep, 10mm rise, 760mm, 31.8mm",
                            SpecModel = "S-Works Carbon XC Mini Rise",
                            SpecType = "HANDLEBARS"
                        },
                        new
                        {
                            SpecId = 21L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = "",
                            SpecModel = "Trail Grips",
                            SpecType = "GRIPS"
                        },
                        new
                        {
                            SpecId = 22L,
                            SpecBrand = "SRAM",
                            SpecCatId = 5L,
                            SpecDescr = "hydraulic disc",
                            SpecModel = "Level Ultimate",
                            SpecType = "FRONT BRAKE"
                        },
                        new
                        {
                            SpecId = 23L,
                            SpecBrand = "SRAM",
                            SpecCatId = 5L,
                            SpecDescr = "hydraulic disc",
                            SpecModel = "Level Ultimate",
                            SpecType = "REAR BRAKE"
                        },
                        new
                        {
                            SpecId = 24L,
                            SpecBrand = "Specialized",
                            SpecCatId = 6L,
                            SpecDescr = "",
                            SpecModel = "Dirt",
                            SpecType = "PEDALS"
                        },
                        new
                        {
                            SpecId = 25L,
                            SpecBrand = "Specialized",
                            SpecCatId = 7L,
                            SpecDescr = "XC Geometry, Rider-First Engineered™, threaded BB, 12x148mm rear spacing, internal cable routing, 100mm of travel",
                            SpecModel = "S-Works FACT 12m",
                            SpecType = "SEAT BINDER"
                        },
                        new
                        {
                            SpecId = 26L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "12-speed",
                            SpecModel = "GX Eagle",
                            SpecType = "CHAIN"
                        },
                        new
                        {
                            SpecId = 27L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "trigger, 12-speed",
                            SpecModel = "X01 Eagle",
                            SpecType = "SHIFT LEVERS"
                        },
                        new
                        {
                            SpecId = 28L,
                            SpecBrand = "SRAM",
                            SpecCatId = 1L,
                            SpecDescr = "12-speed, 10-50t",
                            SpecModel = "XG-1295 Eagle",
                            SpecType = "CASSETTE"
                        },
                        new
                        {
                            SpecId = 29L,
                            SpecBrand = "RockShox",
                            SpecCatId = 2L,
                            SpecDescr = "Position Sensitive, top-adjust Brain Fade, 15x110mm Maxle® Stealth thru-axle, 42mm offset, 100mm of travel",
                            SpecModel = "SID Brain 29",
                            SpecType = "FORK"
                        },
                        new
                        {
                            SpecId = 30L,
                            SpecBrand = "Specialized",
                            SpecCatId = 3L,
                            SpecDescr = "sealed cartridge bearings, 15x110mm spacing, 28h",
                            SpecModel = "",
                            SpecType = "FRONT HUB"
                        },
                        new
                        {
                            SpecId = 31L,
                            SpecBrand = "DT Swiss",
                            SpecCatId = 3L,
                            SpecDescr = "Star Ratchet, 36t engagement, SRAM XD driver body, 12mm thru-axle, 148mm spacing, 28h",
                            SpecModel = "350",
                            SpecType = "REAR HUB"
                        },
                        new
                        {
                            SpecId = 32L,
                            SpecBrand = "DT Swiss",
                            SpecCatId = 3L,
                            SpecDescr = "",
                            SpecModel = "Industry",
                            SpecType = "SPOKES"
                        },
                        new
                        {
                            SpecId = 33L,
                            SpecBrand = "Roval",
                            SpecCatId = 3L,
                            SpecDescr = "25mm internal width, tubeless-ready",
                            SpecModel = "Control Carbon",
                            SpecType = "RIMS"
                        },
                        new
                        {
                            SpecId = 34L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = "Hollow Titanium rails, 143mm",
                            SpecModel = "Body Geometry Power",
                            SpecType = "SADDLE"
                        },
                        new
                        {
                            SpecId = 35L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = " single-bolt, 30.9mm",
                            SpecModel = "Carbon",
                            SpecType = "SEATPOST"
                        },
                        new
                        {
                            SpecId = 36L,
                            SpecBrand = "Specialized",
                            SpecCatId = 4L,
                            SpecDescr = "3D-forged alloy, 4-bolt, 6-degree rise",
                            SpecModel = "XC",
                            SpecType = "STEM"
                        },
                        new
                        {
                            SpecId = 37L,
                            SpecBrand = "SRAM",
                            SpecCatId = 5L,
                            SpecDescr = "hydraulic disc",
                            SpecModel = "Level TLM",
                            SpecType = "FRONT BRAKE"
                        },
                        new
                        {
                            SpecId = 38L,
                            SpecBrand = "Specialized",
                            SpecCatId = 7L,
                            SpecDescr = "Alloy, 34.9mm",
                            SpecModel = "",
                            SpecType = "SEAT BINDER"
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.SpecificationCategory", b =>
                {
                    b.Property<long>("SpecCatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSpecCatActive");

                    b.Property<string>("SpecCatName");

                    b.HasKey("SpecCatId");

                    b.ToTable("SpecificationCategory");

                    b.HasData(
                        new
                        {
                            SpecCatId = 1L,
                            IsSpecCatActive = true,
                            SpecCatName = "Drivetrain"
                        },
                        new
                        {
                            SpecCatId = 2L,
                            IsSpecCatActive = true,
                            SpecCatName = "Suspension"
                        },
                        new
                        {
                            SpecCatId = 3L,
                            IsSpecCatActive = true,
                            SpecCatName = "Wheels"
                        },
                        new
                        {
                            SpecCatId = 4L,
                            IsSpecCatActive = true,
                            SpecCatName = "Cockpit"
                        },
                        new
                        {
                            SpecCatId = 5L,
                            IsSpecCatActive = true,
                            SpecCatName = "Brakes"
                        },
                        new
                        {
                            SpecCatId = 6L,
                            IsSpecCatActive = true,
                            SpecCatName = "Accessories"
                        },
                        new
                        {
                            SpecCatId = 7L,
                            IsSpecCatActive = true,
                            SpecCatName = "Frameset"
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.StoreImages", b =>
                {
                    b.Property<long>("SIId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SIDescription");

                    b.HasKey("SIId");

                    b.ToTable("StoreImages");
                });

            modelBuilder.Entity("BikeStore.Data.Entities.BikeJunction", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.Bike", "BJBike")
                        .WithMany("BikeJunctions")
                        .HasForeignKey("BId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Bike", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.Category", "BCategory")
                        .WithMany("Bikes")
                        .HasForeignKey("BCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bikeStore.Data.Entities.StoreImages", "BImages")
                        .WithMany()
                        .HasForeignKey("BImagesSIId");
                });

            modelBuilder.Entity("bikeStore.Data.Entities.BikeSpecJunction", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.Bike", "BSJBike")
                        .WithMany("BikeSpecJunctions")
                        .HasForeignKey("BSJBikeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bikeStore.Data.Entities.Specification", "BSJSpecification")
                        .WithMany("BikeSpecJunctions")
                        .HasForeignKey("BSJSpecificationSpecId");
                });

            modelBuilder.Entity("bikeStore.Data.Entities.ImgContent", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.StoreImages")
                        .WithMany("SIImeges")
                        .HasForeignKey("StoreImagesSIId");
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Specification", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.SpecificationCategory", "SpecCategory")
                        .WithMany("Specifications")
                        .HasForeignKey("SpecCatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
