// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bikeStore.Data;

namespace BikeStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200301214750_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BikeStore.Data.Entities.BikesColorSize", b =>
                {
                    b.Property<long>("BikeId");

                    b.Property<long>("ColorId");

                    b.Property<long>("SizeId");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BikeId", "ColorId", "SizeId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("SizeId");

                    b.ToTable("BikesColorSize");
                });

            modelBuilder.Entity("BikeStore.Data.Entities.Color", b =>
                {
                    b.Property<long>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorName");

                    b.Property<string>("ColorValue");

                    b.HasKey("ColorId");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("BikeStore.Data.Entities.Size", b =>
                {
                    b.Property<long?>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SizeName");

                    b.Property<string>("SizeValue");

                    b.HasKey("SizeId");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Bike", b =>
                {
                    b.Property<long>("BikeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<long>("CategoryId");

                    b.Property<long?>("ImagesStoreImgId");

                    b.Property<long>("ImgId");

                    b.Property<bool>("IsInStock");

                    b.Property<string>("Model");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("ThumbImgContent");

                    b.HasKey("BikeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImagesStoreImgId");

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            BikeId = 1L,
                            Brand = "Specialized",
                            CategoryId = 5L,
                            ImgId = 0L,
                            IsInStock = true,
                            Model = "S-Works Epic AXS",
                            Price = 1299.6m
                        },
                        new
                        {
                            BikeId = 2L,
                            Brand = "Specialized",
                            CategoryId = 5L,
                            ImgId = 0L,
                            IsInStock = true,
                            Model = "Epic Pro",
                            Price = 899.5m
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.BikesSpecifications", b =>
                {
                    b.Property<long>("BikeId");

                    b.Property<long>("SpecificationId");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("BikeId", "SpecificationId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("SpecificationId");

                    b.ToTable("BikesSpecifications");

                    b.HasData(
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 1L,
                            Id = 1L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 2L,
                            Id = 2L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 3L,
                            Id = 3L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 4L,
                            Id = 4L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 5L,
                            Id = 5L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 6L,
                            Id = 6L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 7L,
                            Id = 7L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 8L,
                            Id = 8L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 9L,
                            Id = 9L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 10L,
                            Id = 10L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 11L,
                            Id = 11L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 12L,
                            Id = 12L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 13L,
                            Id = 13L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 14L,
                            Id = 14L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 15L,
                            Id = 15L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 16L,
                            Id = 16L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 17L,
                            Id = 17L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 18L,
                            Id = 18L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 19L,
                            Id = 19L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 20L,
                            Id = 20L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 21L,
                            Id = 21L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 22L,
                            Id = 22L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 23L,
                            Id = 23L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 24L,
                            Id = 24L
                        },
                        new
                        {
                            BikeId = 1L,
                            SpecificationId = 25L,
                            Id = 25L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 26L,
                            Id = 26L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 2L,
                            Id = 27L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 3L,
                            Id = 28L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 27L,
                            Id = 29L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 28L,
                            Id = 30L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 6L,
                            Id = 31L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 7L,
                            Id = 32L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 29L,
                            Id = 33L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 9L,
                            Id = 34L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 30L,
                            Id = 35L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 31L,
                            Id = 36L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 32L,
                            Id = 37L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 33L,
                            Id = 38L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 14L,
                            Id = 39L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 15L,
                            Id = 40L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 16L,
                            Id = 41L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 34L,
                            Id = 42L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 35L,
                            Id = 43L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 36L,
                            Id = 44L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 20L,
                            Id = 45L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 21L,
                            Id = 46L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 37L,
                            Id = 47L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 23L,
                            Id = 48L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 24L,
                            Id = 49L
                        },
                        new
                        {
                            BikeId = 2L,
                            SpecificationId = 38L,
                            Id = 50L
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Category", b =>
                {
                    b.Property<long>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatDescr");

                    b.Property<string>("CatName");

                    b.Property<bool>("IsCategoryActive");

                    b.Property<long?>("MainCatId");

                    b.HasKey("CatId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CatId = 1L,
                            CatName = "Mountain",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 2L,
                            CatName = "Road",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 3L,
                            CatName = "Active",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 4L,
                            CatName = "Electric",
                            IsCategoryActive = true
                        },
                        new
                        {
                            CatId = 5L,
                            CatName = "Cross Country",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 6L,
                            CatName = "Trail",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 7L,
                            CatName = "Downhill",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 8L,
                            CatName = "Dirt Jump",
                            IsCategoryActive = true,
                            MainCatId = 1L
                        },
                        new
                        {
                            CatId = 9L,
                            CatName = "Performance",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 10L,
                            CatName = "Adventure & Gravel",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 11L,
                            CatName = "Cyclocross",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 12L,
                            CatName = "Triathlon",
                            IsCategoryActive = true,
                            MainCatId = 2L
                        },
                        new
                        {
                            CatId = 13L,
                            CatName = "Fitness",
                            IsCategoryActive = true,
                            MainCatId = 3L
                        },
                        new
                        {
                            CatId = 14L,
                            CatName = "Transport",
                            IsCategoryActive = true,
                            MainCatId = 3L
                        },
                        new
                        {
                            CatId = 15L,
                            CatName = "Comfort",
                            IsCategoryActive = true,
                            MainCatId = 3L
                        },
                        new
                        {
                            CatId = 16L,
                            CatName = "Road",
                            IsCategoryActive = true,
                            MainCatId = 4L
                        },
                        new
                        {
                            CatId = 17L,
                            CatName = "Mountain",
                            IsCategoryActive = true,
                            MainCatId = 4L
                        },
                        new
                        {
                            CatId = 18L,
                            CatName = "Active",
                            IsCategoryActive = true,
                            MainCatId = 4L
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.ImgContent", b =>
                {
                    b.Property<long>("ImgContentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content");

                    b.Property<string>("ImgContentMimeType");

                    b.Property<string>("ImgContentName");

                    b.Property<long>("StoreImgId");

                    b.HasKey("ImgContentId");

                    b.HasIndex("StoreImgId");

                    b.ToTable("ImgContent");
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Specification", b =>
                {
                    b.Property<long>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<string>("Description");

                    b.Property<string>("Model");

                    b.Property<long>("SpecCatId");

                    b.Property<string>("Type");

                    b.HasKey("SpecId");

                    b.HasIndex("SpecCatId");

                    b.ToTable("Specifications");

                    b.HasData(
                        new
                        {
                            SpecId = 1L,
                            Brand = "SRAM",
                            Description = "(Rainbow)",
                            Model = "XX1",
                            SpecCatId = 1L,
                            Type = "CHAIN"
                        },
                        new
                        {
                            SpecId = 2L,
                            Brand = "SRAM",
                            Description = "threaded BB",
                            Model = "DUB",
                            SpecCatId = 1L,
                            Type = "BOTTOM BRACKET"
                        },
                        new
                        {
                            SpecId = 3L,
                            Brand = "QUARQ",
                            Description = "Boost™ 148, DUB, 170/175mm",
                            Model = "XX1 Eagle Power Meter",
                            SpecCatId = 1L,
                            Type = "CRANKSET"
                        },
                        new
                        {
                            SpecId = 4L,
                            Brand = "SRAM",
                            Description = "trigger, 12-speed",
                            Model = "XX1 Eagle AXS",
                            SpecCatId = 1L,
                            Type = "SHIFT LEVERS"
                        },
                        new
                        {
                            SpecId = 5L,
                            Brand = "SRAM",
                            Description = "10-50t",
                            Model = "XG-1299 Eagle",
                            SpecCatId = 1L,
                            Type = "CASSETTE"
                        },
                        new
                        {
                            SpecId = 6L,
                            Brand = "Alloy",
                            Description = "32T",
                            Model = "",
                            SpecCatId = 1L,
                            Type = "CHAINRINGS"
                        },
                        new
                        {
                            SpecId = 7L,
                            Brand = "SRAM",
                            Description = "",
                            Model = "XX1 Eagle AXS",
                            SpecCatId = 1L,
                            Type = "REAR DERAILLEUR"
                        },
                        new
                        {
                            SpecId = 8L,
                            Brand = "RockShox",
                            Description = "top-adjust Brain Fade, tapered carbon crown and steerer, 15x110mm Maxle® Stealth thru-axle, 42mm offset, 100mm of travel",
                            Model = "SID Brain Ultimate",
                            SpecCatId = 2L,
                            Type = "FORK"
                        },
                        new
                        {
                            SpecId = 9L,
                            Brand = "RockShox",
                            Description = "AUTOSAG, 51x257mm",
                            Model = "Custom Micro Brain shock w/ Spike Valve",
                            SpecCatId = 2L,
                            Type = "REAR SHOCK"
                        },
                        new
                        {
                            SpecId = 10L,
                            Brand = "Roval",
                            Description = "sealed cartridge bearings, 15mm thru-axle, 110mm spacing, 24h",
                            Model = "Control SL",
                            SpecCatId = 3L,
                            Type = "FRONT HUB"
                        },
                        new
                        {
                            SpecId = 11L,
                            Brand = "Roval",
                            Description = "DT Swiss Star Ratchet, 54t engagement, SRAM XD driver body, 12mm thru-axle, 148mm spacing, 28h",
                            Model = "Control SL",
                            SpecCatId = 3L,
                            Type = "REAR HUB"
                        },
                        new
                        {
                            SpecId = 12L,
                            Brand = "Presta",
                            Description = "60mm valve",
                            Model = "",
                            SpecCatId = 3L,
                            Type = "INNER TUBES"
                        },
                        new
                        {
                            SpecId = 13L,
                            Brand = "DT Swiss",
                            Description = "Competition Race",
                            Model = "",
                            SpecCatId = 3L,
                            Type = "SPOKES"
                        },
                        new
                        {
                            SpecId = 14L,
                            Brand = "Roval",
                            Description = "hookless carbon, 25mm internal width, tubeless-ready, hand-built",
                            Model = "Control SL",
                            SpecCatId = 3L,
                            Type = "RIMS"
                        },
                        new
                        {
                            SpecId = 15L,
                            Brand = "Specialized",
                            Description = "Control casing, GRIPTON® compound, 60 TPI, 2Bliss Ready, 29x2.3",
                            Model = "Fast Trak",
                            SpecCatId = 3L,
                            Type = "FRONT TIRE"
                        },
                        new
                        {
                            SpecId = 16L,
                            Brand = "Specialized",
                            Description = "Control casing, GRIPTON® compound, 60 TPI, 2Bliss Ready, 29x2.3",
                            Model = "Fast Trak",
                            SpecCatId = 3L,
                            Type = "REAR TIRE"
                        },
                        new
                        {
                            SpecId = 17L,
                            Brand = "Specialized",
                            Description = "carbon fiber rails, carbon fiber base, 143mm",
                            Model = "Body Geometry S-Works Power",
                            SpecCatId = 4L,
                            Type = "SADDLE"
                        },
                        new
                        {
                            SpecId = 18L,
                            Brand = "Specialized",
                            Description = "10mm setback, 30.9mm",
                            Model = "S-Works FACT carbon",
                            SpecCatId = 4L,
                            Type = "SEATPOST"
                        },
                        new
                        {
                            SpecId = 19L,
                            Brand = "Specialized",
                            Description = "alloy, titanium bolts, 6-degree rise",
                            Model = "S-Works SL",
                            SpecCatId = 4L,
                            Type = "STEM"
                        },
                        new
                        {
                            SpecId = 20L,
                            Brand = "Specialized",
                            Description = "6-degree upsweep, 8-degree backsweep, 10mm rise, 760mm, 31.8mm",
                            Model = "S-Works Carbon XC Mini Rise",
                            SpecCatId = 4L,
                            Type = "HANDLEBARS"
                        },
                        new
                        {
                            SpecId = 21L,
                            Brand = "Specialized",
                            Description = "",
                            Model = "Trail Grips",
                            SpecCatId = 4L,
                            Type = "GRIPS"
                        },
                        new
                        {
                            SpecId = 22L,
                            Brand = "SRAM",
                            Description = "hydraulic disc",
                            Model = "Level Ultimate",
                            SpecCatId = 5L,
                            Type = "FRONT BRAKE"
                        },
                        new
                        {
                            SpecId = 23L,
                            Brand = "SRAM",
                            Description = "hydraulic disc",
                            Model = "Level Ultimate",
                            SpecCatId = 5L,
                            Type = "REAR BRAKE"
                        },
                        new
                        {
                            SpecId = 24L,
                            Brand = "Specialized",
                            Description = "",
                            Model = "Dirt",
                            SpecCatId = 6L,
                            Type = "PEDALS"
                        },
                        new
                        {
                            SpecId = 25L,
                            Brand = "Specialized",
                            Description = "XC Geometry, Rider-First Engineered™, threaded BB, 12x148mm rear spacing, internal cable routing, 100mm of travel",
                            Model = "S-Works FACT 12m",
                            SpecCatId = 7L,
                            Type = "SEAT BINDER"
                        },
                        new
                        {
                            SpecId = 26L,
                            Brand = "SRAM",
                            Description = "12-speed",
                            Model = "GX Eagle",
                            SpecCatId = 1L,
                            Type = "CHAIN"
                        },
                        new
                        {
                            SpecId = 27L,
                            Brand = "SRAM",
                            Description = "trigger, 12-speed",
                            Model = "X01 Eagle",
                            SpecCatId = 1L,
                            Type = "SHIFT LEVERS"
                        },
                        new
                        {
                            SpecId = 28L,
                            Brand = "SRAM",
                            Description = "12-speed, 10-50t",
                            Model = "XG-1295 Eagle",
                            SpecCatId = 1L,
                            Type = "CASSETTE"
                        },
                        new
                        {
                            SpecId = 29L,
                            Brand = "RockShox",
                            Description = "Position Sensitive, top-adjust Brain Fade, 15x110mm Maxle® Stealth thru-axle, 42mm offset, 100mm of travel",
                            Model = "SID Brain 29",
                            SpecCatId = 2L,
                            Type = "FORK"
                        },
                        new
                        {
                            SpecId = 30L,
                            Brand = "Specialized",
                            Description = "sealed cartridge bearings, 15x110mm spacing, 28h",
                            Model = "",
                            SpecCatId = 3L,
                            Type = "FRONT HUB"
                        },
                        new
                        {
                            SpecId = 31L,
                            Brand = "DT Swiss",
                            Description = "Star Ratchet, 36t engagement, SRAM XD driver body, 12mm thru-axle, 148mm spacing, 28h",
                            Model = "350",
                            SpecCatId = 3L,
                            Type = "REAR HUB"
                        },
                        new
                        {
                            SpecId = 32L,
                            Brand = "DT Swiss",
                            Description = "",
                            Model = "Industry",
                            SpecCatId = 3L,
                            Type = "SPOKES"
                        },
                        new
                        {
                            SpecId = 33L,
                            Brand = "Roval",
                            Description = "25mm internal width, tubeless-ready",
                            Model = "Control Carbon",
                            SpecCatId = 3L,
                            Type = "RIMS"
                        },
                        new
                        {
                            SpecId = 34L,
                            Brand = "Specialized",
                            Description = "Hollow Titanium rails, 143mm",
                            Model = "Body Geometry Power",
                            SpecCatId = 4L,
                            Type = "SADDLE"
                        },
                        new
                        {
                            SpecId = 35L,
                            Brand = "Specialized",
                            Description = " single-bolt, 30.9mm",
                            Model = "Carbon",
                            SpecCatId = 4L,
                            Type = "SEATPOST"
                        },
                        new
                        {
                            SpecId = 36L,
                            Brand = "Specialized",
                            Description = "3D-forged alloy, 4-bolt, 6-degree rise",
                            Model = "XC",
                            SpecCatId = 4L,
                            Type = "STEM"
                        },
                        new
                        {
                            SpecId = 37L,
                            Brand = "SRAM",
                            Description = "hydraulic disc",
                            Model = "Level TLM",
                            SpecCatId = 5L,
                            Type = "FRONT BRAKE"
                        },
                        new
                        {
                            SpecId = 38L,
                            Brand = "Specialized",
                            Description = "Alloy, 34.9mm",
                            Model = "",
                            SpecCatId = 7L,
                            Type = "SEAT BINDER"
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.SpecificationCategory", b =>
                {
                    b.Property<long>("SpecCatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSpecCatActive");

                    b.Property<string>("SpecCatName");

                    b.HasKey("SpecCatId");

                    b.ToTable("SpecificationCategory");

                    b.HasData(
                        new
                        {
                            SpecCatId = 1L,
                            IsSpecCatActive = true,
                            SpecCatName = "Drivetrain"
                        },
                        new
                        {
                            SpecCatId = 2L,
                            IsSpecCatActive = true,
                            SpecCatName = "Suspension"
                        },
                        new
                        {
                            SpecCatId = 3L,
                            IsSpecCatActive = true,
                            SpecCatName = "Wheels"
                        },
                        new
                        {
                            SpecCatId = 4L,
                            IsSpecCatActive = true,
                            SpecCatName = "Cockpit"
                        },
                        new
                        {
                            SpecCatId = 5L,
                            IsSpecCatActive = true,
                            SpecCatName = "Brakes"
                        },
                        new
                        {
                            SpecCatId = 6L,
                            IsSpecCatActive = true,
                            SpecCatName = "Accessories"
                        },
                        new
                        {
                            SpecCatId = 7L,
                            IsSpecCatActive = true,
                            SpecCatName = "Frameset"
                        });
                });

            modelBuilder.Entity("bikeStore.Data.Entities.StoreImages", b =>
                {
                    b.Property<long>("StoreImgId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("StoreImgId");

                    b.ToTable("StoreImages");
                });

            modelBuilder.Entity("BikeStore.Data.Entities.BikesColorSize", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.Bike", "Bike")
                        .WithMany("ColorSize")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BikeStore.Data.Entities.Color", "Color")
                        .WithMany("BikesColorSize")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BikeStore.Data.Entities.Size", "Size")
                        .WithMany("BikesColorSize")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Bike", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.Category", "Category")
                        .WithMany("Bikes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bikeStore.Data.Entities.StoreImages", "Images")
                        .WithMany()
                        .HasForeignKey("ImagesStoreImgId");
                });

            modelBuilder.Entity("bikeStore.Data.Entities.BikesSpecifications", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.Bike", "Bike")
                        .WithMany("Specifications")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("bikeStore.Data.Entities.Specification", "Specification")
                        .WithMany("BikesSpecifications")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bikeStore.Data.Entities.ImgContent", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.StoreImages", "StoreImages")
                        .WithMany("ImgContents")
                        .HasForeignKey("StoreImgId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("bikeStore.Data.Entities.Specification", b =>
                {
                    b.HasOne("bikeStore.Data.Entities.SpecificationCategory", "SpecCategory")
                        .WithMany("Specifications")
                        .HasForeignKey("SpecCatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
